// byte labels for switches on front panel
#define BANK_MANUAL 1
#define BANK_OFF 0
#define BANK_AUTO 2
#define BANK_ERROR_MANUAL_AND_AUTO 3
#define BANK_TRIGGER_OFF 4
#define BANK_TRIGGER_MANUAL 5
#define BANK_TRIGGER_AUTO 6
#define BANK_ERROR_TRIGGER_MANUAL_AND_AUTO 7

// Device Parameters
#define NBANKS 4 // Capacitor bank groups
#define HV_MIN_VOLTAGE -50000
#define HV_MAX_VOLTAGE 0
#define HV_TIMEOUT 4000

#define CHARGE_TIMEOUT_MS 45000
#define VOLTAGE_MARGIN 200


// COMMAND_CODES
#define COMMAND_GET 0
#define COMMAND_SET 1
#define COMMAND_RESET 2
#define COMMAND_DRY_RUN 4
#define COMMAND_CHARGE 8
#define COMMAND_PULSE 16
#define COMMAND_ABORT 32

// OTHER EVENT CODES
#define HV_BIAS_CHANGE 56
#define SWITCH_STATE_CHANGE 99
#define HEARTBEAT 85

// RESPONSE TYPES
#define OK 0
#define AT_LEAST_ONE_BANK_MANUAL 1
#define WRONG_NUMBER_OF_ARGUMENTS 2
#define INVALID_BANK_NUMBER 3
#define BANK_VOLTAGE_OUT_OF_RANGE 4
#define ATTEMPT_TO_PULSE_WHILST_CHARGING 5
#define ALREADY_PULSING 6
#define TIMED_OUT 7
#define ALREADY_AT_TARGET_VOLTAGE 8
#define ALREADY_CHARGING 9
#define ATTEMPT_TO_CHARGE_WHILST_PULSING 10
#define CHARGE_RATE_ABNORMAL 11
#define BAD_SWITCH_STATE 12
#define ILLEGAL_VALUE_FOR_ARGUMENT 13
#define ABORTED 14

// PARAMETER CODES
#define PULSE_WIDTH 0
#define PULSE_DELAY 1
#define CHARGE_ENABLE 2
#define CHARGE_POWER 4
#define HV_STATE 8
#define HV_VOLTAGE 16
#define BANK_VOLTAGE 32
#define SWITCH_STATE 64
#define GENERAL 70


