// Pin Assignments
#define TRIG1_PROBE CONTROLLINO_D0
#define TRIG2_PROBE CONTROLLINO_D1
#define TRIG3_PROBE CONTROLLINO_D2
#define TRIG4_PROBE CONTROLLINO_D3
#define TRIGHV_PROBE CONTROLLINO_D4

#define PROBE_AUTO CONTROLLINO_A1
#define PROBE_MANUAL CONTROLLINO_A2
#define PROBE_TRIGGER CONTROLLINO_A3

#define STROBE_OUTPUT CONTROLLINO_D18
#define ACTIVE_LED CONTROLLINO_D19

#define CHG_POWER CONTROLLINO_R13
#define CHG_ENBL CONTROLLINO_R14
#define CHG      CONTROLLINO_R15

#define PANEL_HV_MANUAL CONTROLLINO_A12
#define PANEL_HV_AUTO   CONTROLLINO_A13
#define REMOTE_HV_ON    CONTROLLINO_R7
#define HV_ENABLE       CONTROLLINO_R6
#define LOCAL_VOLTAGE_CONTROL CONTROLLINO_R8
#define REMOTE_VOLTAGE_CONTROL CONTROLLINO_R9
#define REMOTE_VREF_0_10V CONTROLLINO_D9 

#define HV_VOLTAGE_DETECT CONTROLLINO_A15
#define HV_CURRENT_DETECT CONTROLLINO_A14

#define ANNOYING_BEEPER CONTROLLINO_D17

#define BANK1_L CONTROLLINO_A4
#define BANK1_U CONTROLLINO_A5
#define BANK2_L CONTROLLINO_A6
#define BANK2_U CONTROLLINO_A7
#define BANK3_L CONTROLLINO_A8
#define BANK3_U CONTROLLINO_A9
#define BANK4_L CONTROLLINO_A10
#define BANK4_U CONTROLLINO_A11

